/* eslint-disable @typescript-eslint/no-require-imports */
/* eslint-disable no-undef */
/** @type {import('tailwindcss').Config} */

export default {
	mode: 'jit',
	content: [
		"./index.html",
		"./src/**/*.{js,ts,jsx,tsx}",
		'./safelist.txt'
	],
	darkMode: 'class',
	theme: {
		fontFamily: {
			ProximaNovaNormal: ["ProximaNovaNormal", "sans-serif"],
			ProximaNovaBold: ["ProximaNovaBold", "sans-serif"],
			ProximaNovaMedium: ["ProximaNovaMedium", "sans-serif"],
			ProvimaNovaThin: ["ProvimaNovaThin", "sans-serif"],
			PoppinsRegular: ["PoppinsRegular", "sans-serif"],
			MartianMono : ["MartianMono", "monospace"],
			sans: [
				'Inter',
				'ui-sans-serif',
				'system-ui',
				'-apple-system',
				'BlinkMacSystemFont',
				'"Segoe UI"',
				'Roboto',
				'"Helvetica Neue"',
				'Arial',
				'"Noto Sans"',
				'sans-serif',
				'"Apple Color Emoji"',
				'"Segoe UI Emoji"',
				'"Segoe UI Symbol"',
				'"Noto Color Emoji"',
			],
			serif: [
				'ui-serif',
				'Georgia',
				'Cambria',
				'"Times New Roman"',
				'Times',
				'serif',
			],
			mono: [
				'ui-monospace',
				'SFMono-Regular',
				'Menlo',
				'Monaco',
				'Consolas',
				'"Liberation Mono"',
				'"Courier New"',
				'monospace',
			],
		},
		screens: {
			ts: "360px",
			'0xs': "380px",
			xs1: "400px",
			xs2: "450px",
			xs: '576px',
			ss: "620px",
			sm: '640px',
			'sm1': "770px",
			md: '768px',
			'2md': '900px',
			md3: "1000px",
			lg: '1024px',
			lg2: "1200px",
			llg: "1300px",
			llg2: "1400px",
			xl: '1280px',
			'2xl': '1536px',
		},
		extend: {
			colors: {
				"fadedText": "#8B8F96",
				'primary': '#41B06E',
				'primary-deep': '#35965D',
				'primary-mild': '#59C882',
				'primary-subtle': '#3CA567',
				'error': 'var(--error)',
				'error-subtle': 'var(--error-subtle)',
				'success': 'var(--success)',
				'success-subtle': 'var(--success-subtle)',
				'info': 'var(--info)',
				'info-subtle': 'var(--info-subtle)',
				'warning': 'var(--warning)',
				'warning-subtle': 'var(--warning-subtle)',
				'neutral': 'var(--neutral)',
				'gray-50': 'var(--gray-200)',
				'gray-100': 'var(--gray-100)',
				'gray-200': 'var(--gray-200)',
				'gray-300': 'var(--gray-300)',
				'gray-400': 'var(--gray-400)',
				'gray-500': 'var(--gray-500)',
				'gray-600': 'var(--gray-600)',
				'gray-700': '#292C2D', // 'var(--gray-700)',
				'gray-800': '#181A1C', // 'var(--gray-800)',
				'gray-900': 'var(--gray-900)',
				'gray-950': '#111315', // 'var(--gray-950)',
				'button-bg': '#41B06E',
			},
			typography: (theme) => ({
				DEFAULT: {
					css: {
						color: theme('colors.gray.500'),
						maxWidth: '65ch',
					},
				},
				invert: {
					css: {
						color: theme('colors.gray.400'),
					},
				},
			}),
		},
	},
	plugins: [
		require('@tailwindcss/typography'),
	],
};
